<Project>
  <PropertyGroup>
    <GatewayPackageVersion>11.0.0-preview.7.26381.103</GatewayPackageVersion>
    <ExtensibleGatewayVersion>11.0.0-preview.7</ExtensibleGatewayVersion>
    <SampleExtensionVersion>11.0.0</SampleExtensionVersion>
    <Copyright>Copyright © 2026 J.Sakamoto, Mozilla Public License 2.0</Copyright>
    <Authors>J.Sakamoto</Authors>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jsakamoto/Toolbelt.Blazor.WebAssembly.ExtensibleGateway/</RepositoryUrl>
  </PropertyGroup>
</Project>
